from __future__ import annotations

import dataclasses
import hashlib
import re
import shlex
from typing import Any

from .models import valid_domain


class NaiveFrontendError(ValueError):
    pass


@dataclasses.dataclass(slots=True)
class NaiveSource:
    auth_pairs: list[tuple[str, str]] = dataclasses.field(default_factory=list)
    hide_ip: bool = False
    hide_via: bool = False
    probe_resistance: bool = False
    upstream: str = ""
    source_sha256: str = ""


def _tokens(raw: str) -> list[str]:
    try:
        return shlex.split(raw, comments=True, posix=True)
    except ValueError as exc:
        raise NaiveFrontendError(f"cannot parse Caddyfile line: {exc}") from exc


def parse_naive_caddyfile(text: str) -> NaiveSource:
    """Parse only the bounded line-oriented structure generated by LucX."""

    if not isinstance(text, str) or not text.strip() or len(text.encode("utf-8")) > 1024 * 1024:
        raise NaiveFrontendError("Naive Caddyfile is empty or exceeds the safe parser limit")
    result = NaiveSource(source_sha256=hashlib.sha256(text.encode("utf-8")).hexdigest())
    stack: list[str] = []
    forward_blocks = 0

    for line_number, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        tokens = _tokens(raw)
        if not tokens:
            continue
        if tokens == ["}"]:
            if not stack:
                raise NaiveFrontendError(f"unbalanced closing brace on line {line_number}")
            stack.pop()
            continue

        opens = tokens[-1] == "{"
        if opens:
            head = tokens[0]
            parent = stack[-1] if stack else ""
            if tokens == ["{"]:
                context = "global"
                if stack:
                    raise NaiveFrontendError(f"unexpected global block on line {line_number}")
            elif not stack:
                context = "site"
            elif head == "log" and parent in {"global", "site"}:
                context = "log"
            elif head == "servers" and parent == "global":
                context = "servers"
            elif head == "route" and parent == "site":
                context = "route"
            elif head == "forward_proxy" and parent == "route":
                context = "forward_proxy"
                forward_blocks += 1
            else:
                raise NaiveFrontendError(f"unsupported block {head!r} on line {line_number}")
            stack.append(context)
            continue

        if "{" in tokens or "}" in tokens:
            raise NaiveFrontendError(f"inline braces are not accepted on line {line_number}")
        context = stack[-1] if stack else ""
        directive = tokens[0]
        if context == "global":
            allowed = {"admin", "skip_install_trust", "auto_https"}
            if directive not in allowed:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "site":
            if directive not in {"bind", "tls"}:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "log":
            if directive not in {"level", "output", "format"}:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "servers":
            if directive != "protocols":
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "forward_proxy":
            if directive == "basic_auth" and len(tokens) == 3:
                result.auth_pairs.append((tokens[1], tokens[2]))
            elif directive == "hide_ip" and len(tokens) == 1:
                result.hide_ip = True
            elif directive == "hide_via" and len(tokens) == 1:
                result.hide_via = True
            elif directive == "probe_resistance" and len(tokens) == 1:
                result.probe_resistance = True
            elif directive == "upstream" and len(tokens) == 2 and not result.upstream:
                result.upstream = tokens[1]
            else:
                raise NaiveFrontendError(
                    f"unsupported forward_proxy directive {directive!r} on line {line_number}"
                )
        else:
            raise NaiveFrontendError(f"directive {directive!r} is outside an allowed block")

    if stack:
        raise NaiveFrontendError("Naive Caddyfile has unclosed blocks")
    if forward_blocks != 1:
        raise NaiveFrontendError("Naive Caddyfile must contain exactly one forward_proxy block")
    if not result.auth_pairs:
        raise NaiveFrontendError("Naive forward_proxy has no basic_auth entries")
    return result


def _top_level_blocks(text: str) -> list[tuple[str, str]]:
    blocks: list[tuple[str, str]] = []
    depth = 0
    start = 0
    prefix_start = 0
    quote = ""
    escaped = False
    for index, character in enumerate(text):
        if escaped:
            escaped = False
            continue
        if character == "\\" and quote:
            escaped = True
            continue
        if character in {'"', "'"}:
            if quote == character:
                quote = ""
            elif not quote:
                quote = character
            continue
        if quote:
            continue
        if character == "{":
            if depth == 0:
                prefix = text[prefix_start:index].strip()
                start = index + 1
            depth += 1
        elif character == "}":
            depth -= 1
            if depth < 0:
                return []
            if depth == 0:
                blocks.append((prefix, text[start:index]))
                prefix_start = index + 1
    return blocks if depth == 0 else []


def supports_native_decoy(text: str) -> bool:
    for prefix, body in _top_level_blocks(text):
        if not prefix:
            continue
        has_proxy = bool(re.search(r"(?:^|[{}\n])\s*forward_proxy\s*\{", body))
        has_files = bool(re.search(r"(?:^|[{}\n])\s*file_server(?:\s|$)", body))
        if has_proxy and has_files:
            return True
    return False


def _caddy_quote(value: Any) -> str:
    text = str(value)
    if any(character in text for character in ("\x00", "\r", "\n")):
        raise NaiveFrontendError("newline or NUL in Caddy token")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_managed_naive_caddyfile(
    source: NaiveSource,
    *,
    domain: str,
    listen_port: int,
    cert_path: str,
    key_path: str,
    site_root: str,
) -> str:
    domain = str(domain).strip().lower().rstrip(".")
    if not valid_domain(domain) or not 1 <= int(listen_port) <= 65535:
        raise NaiveFrontendError("invalid managed Naive domain or listener port")
    for path in (cert_path, key_path, site_root):
        if not str(path).startswith("/"):
            raise NaiveFrontendError("managed Naive paths must be absolute")
    lines = [
        "{",
        "    admin off",
        "    skip_install_trust",
        "    auto_https off",
        "    servers {",
        "        protocols h1 h2",
        "    }",
        "}",
        "",
        f":{int(listen_port)}, {_caddy_quote(domain + ':' + str(int(listen_port)))} {{",
        "    bind 127.0.0.1",
        f"    tls {_caddy_quote(cert_path)} {_caddy_quote(key_path)}",
        "    route {",
        "        @browser method GET HEAD",
        "        handle @browser {",
        f"            header X-LucX-Decoy {_caddy_quote(domain)}",
        f"            root * {_caddy_quote(site_root)}",
        "            file_server",
        "        }",
        "        forward_proxy {",
    ]
    for user, password in source.auth_pairs:
        lines.append(f"            basic_auth {_caddy_quote(user)} {_caddy_quote(password)}")
    if source.hide_ip:
        lines.append("            hide_ip")
    if source.hide_via:
        lines.append("            hide_via")
    if source.probe_resistance:
        lines.append("            probe_resistance")
    if source.upstream:
        lines.append(f"            upstream {_caddy_quote(source.upstream)}")
    lines.extend(["        }", "    }", "}"])
    return "\n".join(lines) + "\n"


def render_naive_frontend_unit(*, inbound_id: int, binary_path: str) -> str:
    if int(inbound_id) <= 0 or not str(binary_path).startswith("/"):
        raise NaiveFrontendError("invalid Naive unit identity or binary path")
    config = f"/etc/lucx-post-configurator/naive/naive-{int(inbound_id)}.caddyfile"
    state_name = f"lucx-naive-decoy-{int(inbound_id)}"
    data = f"/var/lib/{state_name}"
    return f"""[Unit]
Description=LucX managed Naive browser frontend for inbound {int(inbound_id)}
After=network.target

[Service]
Type=simple
User=root
Group=root
UMask=0077
Environment=XDG_DATA_HOME={data}
Environment=HOME={data}
Environment=XDG_CONFIG_HOME={data}/config
StateDirectory={state_name}
StateDirectoryMode=0700
ExecStart={binary_path} run --config {config} --adapter caddyfile
Restart=on-failure
RestartSec=2s
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=read-only
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
LockPersonality=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

[Install]
WantedBy=multi-user.target
"""


def frontend_sync_state(expected_sha256: str, current_sha256: str) -> str:
    if not re.fullmatch(r"[0-9a-f]{64}", str(expected_sha256 or ""), re.IGNORECASE):
        return "blocked"
    if not re.fullmatch(r"[0-9a-f]{64}", str(current_sha256 or ""), re.IGNORECASE):
        return "blocked"
    return "ready" if expected_sha256.lower() == current_sha256.lower() else "needs_sync"
